name: appenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi
      - openai
      - requests
      - pypdf
      - uvicorn[standard]
      - python-dotenv
      - psycopg[binary]
      - python-multipart
      - email-validator
      - pinecone
